from app.domain.exceptions.base import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    DomainError,
    ExternalServiceError,
    InvalidValueError,
    NotFoundError,
    ServiceUnavailableError,
)
from app.domain.exceptions.business import (
    AlreadyRegisteredToEventError,
    EmailAlreadyRegisteredError,
    EventCannotBeRemovedError,
    EventCapacityBelowRegistrationsError,
    EventCapacityExceededError,
    EventNotEditableError,
    EventNotOpenForRegistrationError,
    ImageStorageError,
    ImageStorageUnavailableError,
    InvalidCredentialsError,
    InvalidEventStatusTransitionError,
    InvalidTokenError,
)

__all__ = [
    "AlreadyRegisteredToEventError",
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "DomainError",
    "EmailAlreadyRegisteredError",
    "EventCannotBeRemovedError",
    "EventCapacityBelowRegistrationsError",
    "EventCapacityExceededError",
    "EventNotEditableError",
    "EventNotOpenForRegistrationError",
    "ExternalServiceError",
    "ImageStorageError",
    "ImageStorageUnavailableError",
    "InvalidCredentialsError",
    "InvalidEventStatusTransitionError",
    "InvalidTokenError",
    "InvalidValueError",
    "NotFoundError",
    "ServiceUnavailableError",
]
